### PR TITLE
Add ReJSON data viewing support

### LINKED ISSUE #371: ReJSON tree view support
Are there any plans of having the possibility to view ReJSON structures as a tree in redis commander? I wonder if it is a popular demand.

### PR DESCRIPTION
**Pull request by funkyfisch**
- Add ReJSON view ejs template
  - Add copy JSON button for easy clipboarding
  - Add ReJSON-RL type of key for handling in back-end

Resolve #371

### CODE REVIEW

**Comment by sseide** [comment]
Thanks - i'll hava a look into it

**Comment by funkyfisch** [comment]
Alright! Since I am at it, should I also mention it in the Changelog, under ##next version, ### enhancements? Or should I only write a line about it in the Readme?

**Comment by sseide** [comment]
yes please - forgot changelog...

**Comment by funkyfisch** [comment]
The force push is purely since I wanted to simply amend the same commit ( I am not very familiar with github workflow in such a situation - we use --amend a lot at work when working on a single change )

**Comment by sseide** [comment]
Thanks!

**Comment by sseide** [comment]
Note to myself - add documentation page about steps to do for adding new redis datatypes...

**Pull request merged**
