### PR TITLE
update alpine and ejs with updates to layout file to support new version

### PR DESCRIPTION
**Pull request by ramijebara**
Some minor updates. I hope you find them useful!
- Built and tested locally.

### CODE REVIEW

**Comment by sseide** [comment]
Thanks for the PR - but some questions
- alpine 3.15 uses new Nodejs 16 - how much have you tested it and everything is working with the new release?
  The current container uses Nodejs12 and we ourself use 14 a lot, therefore know its working with these release - meaning an update to Alpine 3.14 at max is save...
- nodejs12 has support for next half a year, therefore no update needed by now but has to be plannend (and done) within this timeframe
- regarding the update to ejs, i hoped for a newer 3.x version without all these new dependencies (2.7 has no dependencies) but it seems there will be no explicit ejs-cli package to remove all these unneeded deps. And the one security warning in ejs 2.7 for some render parameter does not apply to redis commander as far as i can see.

**Comment by ramijebara** [comment]
> Thanks for the PR - but some questions
> 
> * alpine 3.15 uses new Nodejs 16 - how much have you tested it and everything is working with the new release?
>   The current container uses Nodejs12 and we ourself use 14 a lot, therefore know its working with these release - meaning an update to Alpine 3.14 at max is save...
> * nodejs12 has support for next half a year, therefore no update needed by now but has to be plannend (and done) within this timeframe
> * regarding the update to ejs, i hoped for a newer 3.x version without all these new dependencies (2.7 has no dependencies) but it seems there will be no explicit ejs-cli package to remove all these unneeded deps. And the one security warning in ejs 2.7 for some render parameter does not apply to redis commander as far as i can see.

All good points. Thanks for taking a look! 

In regards to your points ..  ejs, I updated because of the security warning, your intuition is correct there. alpine update was to get to the node version I am using. Not a huge technical reason. 

In terms of testing, tested locally and it seemed to perform about the same. 

That said, redis-commander is a a new tool for me so there is a good chance I missed something so I understand the hesitation.

If you do not think these are useful changes please feel free to decline. No issues here .. just trying to help.

**Comment by sseide** [comment]
Thanks for the help - and good to hear it is working on your side with Node16. There where problems between some Node releases in the past. And because an update to the alpine images is needed within the next months it would be good to just go to the last version if possible. I will have a deeper look into it over the week.

For ejs - we need to do something to - seeing the security warning by all scanners (even if its not vulnerable) is nothing for the long run. Will decide there too.

**Comment by ramijebara** [comment]
Thank you and I understand. I will also continue using and testing from my side and report back any issues I see.

**Pull request merged**
