### PR TITLE
fix(chart): Use autoscaling/v2

### PR DESCRIPTION
**Pull request by Voziv**
autoscaling/v2 was promoted to GA back in kubernetes 1.23 and is no longer available as of kubernetes 1.26

### CODE REVIEW

**Comment by Voziv** [comment]
I've also swapped the order of the cpu and memory metrics.

Kubernetes orders the HPA metrics with memory coming before cpu after the manifest is applied. This causes tools like argocd to think there are changes it needs to sync because the order of the list is different.

**Comment by Voziv** [comment]
> Its needed with lots of older kubernetes versions out there like with OpenShift and other not running on 1.23. Here the chart should not fail.

Good point, I hadn't considered that. I'll update this to include version checks.

**Comment by Voziv** [comment]
I think that should do it. I was able to figure out how to generate the docs, but I had to manually update the `values.schema.json`. No clue what tool is used to generate that unfortately.

**Comment by sseide** [comment]
Many thanks for your work. It looks good now.

As you might have figured out the helm docs are generated by "helm-docs" tool with the script within the ".github/" directory. There is a GitHub action to make sure docs are updated too if chart is changed.

But the json schema file is created manually. There is no tool doing it automatically unfortunately. I will add some
documentation and links on how to create this file.

**Pull request merged**
