### PR TITLE
Fix for resize bug

### PR DESCRIPTION
**Pull request by asferas**
If sidebar border moved right, key selection moves buttons Delete Key and view mode tree behind sidebar

### CODE REVIEW

**Comment by sseide** [comment]
Cannot reproduce the described behaviour. What Browser and Operation System do you use?

During normal operation the `left` property is overwritten on the element itself (therefor the css value at `itemActionBar` is ignored everytime a resize event occures (redisCommander.js method resizeApp line 969 and lines 987-988).
https://github.com/joeferner/redis-commander/blob/a046c60afa473d00ba434ff2c8482bc80bad46f6/web/static/scripts/redisCommander.js#L969-L988
Change itself seems reasonable through as property `lelf`' is set on parent element too. But `resizeApp()` method should not overwrite the `itemActionBar` anymore than? And same goes for `width` property - better set to `inherit` too?

**Comment by asferas** [comment]
Chrome 61 & Win 10. IOS have same problem. _width: 100%_ and _width: inherit_ equals, both of them inherits #body width property

**Comment by sseide** [comment]
Cannot reproduce at Win10/Chrome, seems to be a timing problem when there are no other errors at javascript console of browser...

Please commit this additional changes to your branch:
* CSS  - set `#itemActionBar.width` to inherit too
* remove `#itemActionBar` inside Javascript method `resizeApp()` to only set width/left property of parent `#body` element

Afterwards i'll merge it.

Thanks

**Comment by asferas** [comment]
Done

**Pull request merged**
