### PR TITLE
Added basic Redis Streams (v5.0+) support

### PR DESCRIPTION
**Pull request by adioanca**
Create/View Redis Streams, add/delete/navigate [to] entry.

Thought this basic Redis Streams support could be useful to someone.

I've coded this because I need to see/check Redis streams @work. And for my current requirements, this basic support it's enough - hope development continues on Github.

Please note that I'm a beginner in WEB programming. ;)

Glad to help! Regards,
Adi.

### CODE REVIEW

**Comment by sseide** [comment]
Many thanks for that - will have a lok at it and ping you back if there is something before i merge it

**Comment by sseide** [comment]
Hi,
here are some small remarks, after these are fixed i'll merge it:

* `lib/routes/apiv1.js` - line 505-506 - isNan() function already returns a boolean value, remove '<0' comparison
* `bin/redis-commander.js` - do not remove `require('ioredis')`, is needed in line 305
* `web/static/scripts/redisCommander.js`
  * line 309-320 - please combine booth "if x==='stream' else" statements into one
  * line 431-440 - remove comments if check is not needed (code cleanup)
* `web/static/templates/editStream.ejs` - you commented out some buttons. Are they unneeded or may be usefull later to navigate back and forth in time? If unneeded please remove the `if(false)` blocks for cleanup
* `views/modals/addKeyModal.ejs` - you renamed `#addKeyIsJson` to `#addKeyValueIsJson` and `#addKeyNameIsJson` but missed reference in `web/static/scripts/redisCommander.js` line 295. Should be duplicated and renamed there too?

Finally - just for understanding - your comment at the start of `lib/util.js` - what does this mean "patch until support is out"?

Many thanks for the new features.

**Comment by adioanca** [comment]
Hi,

As I said above, I'm a beginner in WEB/NodeJS/Javascript programming, my background is in C/C++, I just hacked :) redis-commander so that I can see and modify Redis Streams.

If you want to merge that code, **first, please review and refactor it how you see fit**.

Answering some of your questions,

- `require ioredis` & `"patch until support is out"` - ioredis does not have Redis Streams support yet. I used the approach from [HFX-Bus](https://github.com/exocet-engineering/hfx-bus/blob/master/lib/add-streams-to-ioredis.js) - probably they should be mentioned in release notes.

- `web/static/templates/editStream.ejs` - I haven't implemented navigation by *count*, just jumping to a Stream ID and show default number of items.

- `views/modals/addKeyModal.ejs` - can't figure out now... if you think there's a problem, please patch it

Here are some of the known issues:
- Global `Add Stream` modal is not showing the correct fields for the given feature. It defaults to set/get fields even though "Stream" is selected in the dropdown.
- Double clicking on `<tr>` will open the edit modal. When one wants to copy the Stream ID 13123210000000-0 by double clicking and CTRL+C, he/she can't because the modal opens. Maybe the `<td>` with the stream ID should be excluded from the *double click to edit area*? Maybe change the background color the `<td>`s that can be double clicked for editing? And edit button for each row? Don't know...

Last but not least - **AWESOME project** my congrats! THANK YOU!
PS: if redis-commander adds Streams support, I think it's about the first GUI to have it! ;)

**Comment by sseide** [comment]
Thanks

> As I said above, I'm a beginner in WEB/NodeJS/Javascript programming, my background is in C/C++, I just hacked :)

And was quit good :-) Only found two minor bugs and one where you remove a bit to much
I would like to ask you to just add another commit to your branch fixing these and than it can be merged.

Just pointed these out as learning by doing your own errors is often more helpful than me silently fixing these... And - as soon as i merge this new docker images will be automatically build where people may download broken ones (until i get this fixed).

Thanks for the infos - i will add a remark for this (HFX-Bus is Apache license, no problem there) and look into the issues you mentioned.

Question about Double clicking items - as you cannot modifiy them it seems better to not open modal and just add delete button instead at the end of the line? Than text can be selected as usual. What do you think? I can rework it later...

**Comment by adioanca** [comment]
> I would like to ask you to just add another commit to your branch fixing these and than it can be merged.

Sure, point me to the changes.

Another approach is to take my changes, edit them in your (temp)branch and do the commit when you think it's all good & tested.

> Question about Double clicking items - as you cannot modify them it seems better to not open modal and just add delete button instead at the end of the line? Than text can be selected as usual. What do you think? I can rework it later...

I think that's a good idea. I also thought about it, but didn't want to modify your layout. Now that you propose that, I can only encourage you :grin:

**Comment by sseide** [comment]
@adioanca - i merged your PR into my branch and changed the delete procedure as mentioned - can you have a look if it works for you? If its ok i will merge this one into master branch.

https://github.com/sseide/redis-commander/tree/streams

Thanks

**Comment by vflopes** [comment]
Hello everyone, I am the author of HXF-Bus, if you need any support with the implementation of Redis Streams feel free to contact me. On the licensing questions I answered @sseide : https://github.com/exocet-engineering/hfx-bus/issues/4

**Comment by adioanca** [comment]
Hi,

@sseide I played a bit with it and everything works great. Thank you!

@vflopes Thank you for the stream "addon"! I've searched for a couple hours how to do Redis Streams in node.js, and boy I was happy when I've found your code! 🎉. Since you have a lot more experience with Redis Streams, maybe you could suggest what remains to be done for complete Streams support in Redis Commander?

Thank you all! 🤗

**Comment by sseide** [comment]
Ok, new version and docker images contains stream support now.Thanks.

@vflopes - did you tried to create a PullRequest to ioredis project to get it into it? I found some references in there issue board about adding stream related commands starting mid 2018 but it was not done until now...

**Comment by vflopes** [comment]
@adioanca yes man, there's a lack of support to Redis Streams, I'm impressed with this. Redis Streams are really powerful and I see no reason to this lack of support by community :open_mouth:. I've never used Redis Commander, I will set up the project today to see it in action so I can be more useful in this issue ok? :smiley: 

@sseide I thought to do this, but ioredis uses another library to provide it's commands: https://www.npmjs.com/package/redis-commands and I didn't have time to dig into. If it was simply as I did in my project the PR would be easy as copy and paste (and test :laughing:). But you have reason, due to time that this issue is not being addressed by any member, I think it's time to put hands on. Redis Streams PR is coming soon!

**Pull request merged**
